### ISSUE TITLE
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'line' > Overload resolution failed:

### ISSUE THREAD

**Issue by heishen666** [hongyaohongyao/smart_classroom#1]
<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\heishen\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\heishen\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\smart_classroom-master\detection_system\alphapose\utils\writer.py", line 201, in update
    self.draw_pose(self.pose_estimator, img, pose_list)
  File "F:\smart_classroom-master\detection_system\alphapose\utils\writer.py", line 381, in draw_pose
    pose_estimator.draw_axis(
  File "F:\smart_classroom-master\detection_system\pose_estimation\pose_estimator.py", line 282, in draw_axis
    cv2.line(img, tuple(axisPoints[3].ravel()), tuple(
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

**Comment by heishen666** [comment]
救救孩子

**Comment by hongyaohongyao** [comment]
把opecv版本降到4.5.1
