### ISSUE TITLE
摄像头调用

### ISSUE THREAD

**Issue by zhangchufeng** [hongyaohongyao/smart_classroom#21]
除了人脸注册，其他的都调用不了摄像头，本地视频也放不了是怎么回事啊
动态点名的时候是这样
视频源帧率:  30.0
Exception in thread Thread-13:
Traceback (most recent call last):
File "D:\anaconda\envs\123\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "D:\anaconda\envs\123\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "D:\smart_classroom_demo-master\smart_classroom_demo-master\pipeline_module\core\base_module.py", line 102, in _run
execute_result = self.process_data(task_data.data) if execute_condition else task_data.task_flag
File "D:\smart_classroom_demo-master\smart_classroom_demo-master\pipeline_module\face_match_module.py", line 22, in process_data
raw_face_labels = np.argmin(face_distances, axis=1) if face_distances.shape[0] > 0 else np.array([])
File "<array_function internals>", line 180, in argmin
File "D:\anaconda\envs\123\lib\site-packages\numpy\core\fromnumeric.py", line 1312, in argmin
return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
File "D:\anaconda\envs\123\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

**Comment by zhangchufeng** [comment]
作弊检测和专注度分析的摄像头调不出来怎么办，播放本地视频的时候闪退，人脸不能注册

**Comment by hongyaohongyao** [comment]
> 作弊检测和专注度分析的摄像头调不出来怎么办，播放本地视频的时候闪退，人脸不能注册

可能是版本问题。这个仓库没有人脸注册功能，你可以试试这个项目https://github.com/hongyaohongyao/smart_classroom_demo

**Comment by zhangchufeng** [comment]
专注度分析的时候一直显示timer

**Comment by zhangchufeng** [comment]
> > 作弊检测和专注度分析的摄像头调不出来怎么办，播放本地视频的时候闪退，人脸不能注册
> 
> 可能是版本问题。这个仓库没有人脸注册功能，你可以试试这个项目 https://github.com/hongyaohongyao/smart_classroom_demo

你好，请问是什么需要改版本啊，python的版本按照这个网址里面改了还是不行啊

**Comment by hongyaohongyao** [comment]
> > > 作弊检测和专注度分析的摄像头调不出来怎么办，播放本地视频的时候闪退，人脸不能注册
> > 
> > 
> > 可能是版本问题。这个仓库没有人脸注册功能，你可以试试这个项目 https://github.com/hongyaohongyao/smart_classroom_demo
> 
> 你好，请问是什么需要改版本啊，python的版本按照这个网址里面改了还是不行啊

每个库按照[requirements.txt](https://github.com/hongyaohongyao/smart_classroom_demo/blob/master/requirements.txt)里面的版本
