### ISSUE TITLE
No such file or directory: './weights/classroom_action_lr_front_v1.pth'

### ISSUE THREAD

**Issue by FrozenZero** [hongyaohongyao/smart_classroom#3]
classroom_action_lr_front_v1.pth和classroom_action_lr_side_v1.pth可以从哪里获取到？
Traceback (most recent call last):
  File "E:/ml/pose/smart_classroom-master/detection_system/demo_inference.py", line 21, in <module>
    from alphapose.utils.writer import DataDealer
  File "E:\ml\pose\smart_classroom-master\detection_system\alphapose\utils\writer.py", line 14, in <module>
    from kp_analysis import action_classifier_v2 as action_classifier
  File "E:\ml\pose\smart_classroom-master\detection_system\kp_analysis\action_classifier_v2.py", line 9, in <module>
    classroom_action_classifier.load_state_dict(torch.load(classroom_action_classifier_path))
  File "E:\ml\envs\psrgpu\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\ml\envs\psrgpu\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\ml\envs\psrgpu\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './weights/classroom_action_lr_front_v1.pth'

Process finished with exit code 1

**Comment by hongyaohongyao** [comment]
https://pan.baidu.com/s/1X6TR2jiqdqg3Zi8wl7mkxw 好的，我在这里加入了这些权重文件

**Comment by FrozenZero** [comment]
> https://pan.baidu.com/s/1X6TR2jiqdqg3Zi8wl7mkxw 好的，我在这里加入了这些权重文件
发现还有新的缺失：如下所示：
Traceback (most recent call last):
  File "E:/ml/pose/smart_classroom-master/detection_system/demo_inference.py", line 218, in <module>
    tracker = Tracker(tcfg, args)
  File "E:\ml\pose\smart_classroom-master\detection_system\trackers\tracker_api.py", line 207, in __init__
    load_pretrained_weights(self.model, self.opt.loadmodel)
  File "E:\ml\pose\smart_classroom-master\detection_system\trackers\utils\utils.py", line 701, in load_pretrained_weights
    checkpoint = load_checkpoint(weight_path)
  File "E:\ml\pose\smart_classroom-master\detection_system\trackers\utils\utils.py", line 671, in load_checkpoint
    raise FileNotFoundError('File is not found at "{}"'.format(fpath))
FileNotFoundError: File is not found at "trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"

请问下这个缺失的模型是干什么用的？可以提供一下不？谢谢咯

**Comment by hongyaohongyao** [comment]
> > https://pan.baidu.com/s/1X6TR2jiqdqg3Zi8wl7mkxw 好的，我在这里加入了这些权重文件
> > 发现还有新的缺失：如下所示：
> > Traceback (most recent call last):
> > File "E:/ml/pose/smart_classroom-master/detection_system/demo_inference.py", line 218, in 
> > tracker = Tracker(tcfg, args)
> > File "E:\ml\pose\smart_classroom-master\detection_system\trackers\tracker_api.py", line 207, in **init**
> > load_pretrained_weights(self.model, self.opt.loadmodel)
> > File "E:\ml\pose\smart_classroom-master\detection_system\trackers\utils\utils.py", line 701, in load_pretrained_weights
> > checkpoint = load_checkpoint(weight_path)
> > File "E:\ml\pose\smart_classroom-master\detection_system\trackers\utils\utils.py", line 671, in load_checkpoint
> > raise FileNotFoundError('File is not found at "{}"'.format(fpath))
> > FileNotFoundError: File is not found at "trackers/weights/osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth"
> 
> 请问下这个缺失的模型是干什么用的？可以提供一下不？谢谢咯
> @hongyaohongyao

https://github.com/hongyaohongyao/smart_classroom#2-human-reid-based-tracking-recommended是这个，用来做重识别的

**Comment by randy-xyz** [comment]
> https://pan.baidu.com/s/1X6TR2jiqdqg3Zi8wl7mkxw 好的，我在这里加入了这些权重文件

请问这个百度网盘的链接的密码是什么
